# Ingress Controller for Load Balancing
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mercato-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/websocket-services: "mercato-backend-service"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rate-limit: "1000"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
spec:
  tls:
  - hosts:
    - mercato.trading
    - api.mercato.trading
    secretName: mercato-tls
  rules:
  - host: mercato.trading
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mercato-frontend-service
            port:
              number: 3000
  - host: api.mercato.trading
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mercato-backend-service
            port:
              number: 3001

---
# Certificate Issuer for TLS
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@mercato.trading
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
