services:
  app:
    build: .
    ports:
      - "3002:3002"  # Expose your app on port 3002
    env_file:
    - .env # Connect to Redis container
    
    environment:
      - NODEMON_LEGACY_WATCH=1
    volumes:
      - ./src:/app/src
   
    depends_on:
      #- db  # App depends on PostgreSQL
      - redis  # App depends on Redis

  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: local
  #     POSTGRES_DB: mydatabase  # Your database name
  #   volumes:
  #     - db_data:/var/lib/postgresql/data  # Persist data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"  # Expose Redis on port 6379

volumes:
  db_data:  # To persist PostgreSQL data
